### PR TITLE
Bump version using conda_r_skeleton_helper

### PR DESCRIPTION
**Pull request by ConorIA**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (`@conda-forge-admin, please rerender`)
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by dpryan79** [comment]
@bgruening Can you merge this if you get a chance? It's a dependency of a dependency for a bioconda package.

**Comment by bgruening** [comment]
Of course. Btw. do you think we should also pin the BioC recipes to r-base=3.5?

**Comment by dpryan79** [comment]
Isn't that already happening via the build config yaml?

**Comment by bgruening** [comment]
True definitely need sleep.

**Comment by dpryan79** [comment]
Ah, you mean so they don't build for 3.4, probably. I would say we should only do that for new bioconductor packages (they likely won't build for 3.4 anyway). Generally you don't need to update R for a few bioconductor releases, so there's no need to strictly require 3.5.

**Comment by bgruening** [comment]
Afaik, there BioC requires officially a fixed R version, usually the latest. As we build for multiple version this could also yield to problems. I'm not aware of such restrictions of r-* pkgs (in general). So it might be safer and faster to just build for latest R all BioC pkgs. But let me sleep over this.

**Comment by ConorIA** [comment]
This doesn't seem to have built for R 3.5.1 do we need to re-render again?

**Comment by dpryan79** [comment]
Looks like it, yes.

**Pull request merged**
